### ISSUE TITLE
PR #59 Introduced a bug - line order incorrect

### ISSUE THREAD

**Issue by Kamilczak020** [HorizonShadow/YuelaBot#60]
Because I dun goofed, when the last term of !urban command is numeric, index is extracter AFTER we wipe if from `term` instead of before, rendering it useless.

**Comment by HorizonShadow** [comment]
I already fixed your bullshit I merged

**Comment by HorizonShadow** [comment]
https://github.com/HorizonShadow/YuelaBot/blob/master/commands/urban_command.rb
