### ISSUE TITLE
a REBEL-like version of !!s where it runs a list of regexes instead of just one

### ISSUE THREAD

**Issue by HorizonShadow** [HorizonShadow/YuelaBot#97]
Added by kendfrey from Java Fans Gathering#general

**Comment by kendfrey** [comment]
Example:

> A: I don't think that's a good idea.
> B: !!s/ don't//ood/reat/
> bot: I think that's a great idea.

The hard part is identifying the message to apply it to, since any message becomes a valid input.

**Comment by kendfrey** [comment]
Proposed format: `!!s;<msgid>/regex1/replace1/regex2/replace2/.../[flags]`
